version: 2
jobs:
  build:
    docker:
      - image: viniciusam/oracledb:client-tools
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
      - image: viniciusam/oracledb:11g-xe-r2
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: sql -v
      - run: java -version
      - run: |
          sql system/oracle <<EOF
          select sysdate from dual;
          exit;
          EOF
workflows:
  version: 2
  build_and_test:
    jobs:
      - build